# Generated by Django 3.2 on 2021-07-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('aadhar', models.IntegerField()),
                ('vaccinename', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('zone', models.IntegerField()),
                ('dose', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
